Repository GatorEducator/gatorgradle, pull requests merged in 2019-05, with the labels that each got.

#49 Polish documentation and update the output from DependencyManager.
  .travis.yml
  src/main/java/org/gatorgradle/internal/DependencyManager.java
Labels: documentation, enhancement

#50 Fix checkout bug in dependency management
  src/main/java/org/gatorgradle/internal/DependencyManager.java
Labels: bug

#51 Fix Version Changing
  README.md
  gradle.properties
  src/main/java/org/gatorgradle/task/GatorGradleTask.java
Labels: bug, critical
