Repository GatorEducator/gatorgradle, pull requests merged in 2019-12, with the labels that each got.

#63 Feature/task gradle report
  src/main/java/org/gatorgradle/GatorGradlePlugin.java
  src/main/java/org/gatorgradle/config/GatorGradleConfig.java
  src/main/java/org/gatorgradle/display/CommandOutputSummary.java
  src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java
  src/main/java/org/gatorgradle/task/GatorGradleReportTask.java
  src/main/java/org/gatorgradle/task/GatorGradleTask.java
Labels: enhancement, feature

#65 Upgrade `ru.vyarus.quality` version
  build.gradle
Labels: critical, infrastructure

#66 Merge recent master changes into feature/upload-results
  build.gradle
Labels: infrastructure

#53 WIP: Upload a report to a configured endpoint
  .travis.yml
  README.md
  gradle.properties
  gradle/config/spotbugs/exclude.xml
  src/main/java/org/gatorgradle/GatorGradlePlugin.java
  src/main/java/org/gatorgradle/config/ConfigMap.java
  src/main/java/org/gatorgradle/config/GatorGradleConfig.java
  src/main/java/org/gatorgradle/display/CheckResult.java
  src/main/java/org/gatorgradle/display/CommandOutputSummary.java
  src/main/java/org/gatorgradle/internal/Dependency.java
  src/main/java/org/gatorgradle/internal/DependencyManager.java
  src/main/java/org/gatorgradle/task/GatorGradleGradeTask.java
  src/main/java/org/gatorgradle/task/GatorGradleReportTask.java
  src/main/java/org/gatorgradle/task/GatorGradleTask.java
  src/main/java/org/gatorgradle/util/StringUtil.java
Labels: feature, minor
